version: 1.0
runtime: nodejs18

build:
  commands:
    build:
      - npm ci
      - npm run build:core
      - npm run build:file-exchange
      - npm run build:api
      - cd packages/api && npx prisma generate

run:
  runtime-version: 18
  command: npm run start:api
  network:
    port: 3001
    env: PORT
  env:
    - name: NODE_ENV
      value: production
    - name: DATABASE_URL
      value: "{{resolve:secretsmanager:halcyon-rcm/database:SecretString:url}}"
    - name: JWT_SECRET
      value: "{{resolve:secretsmanager:halcyon-rcm/jwt:SecretString:secret}}"
